version: "3.7"

services:
  phoenix:
    build:
      context: .
    env_file:
      - docker.env
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/ager
      DATABASE_USER: postgres
      DATABASE_PASS: postgres
      DATABASE_NAME: ager
      DATABASE_PORT: 5432
      DATABASE_HOST: db
      PORT: 4444
    ports:
      - "4444:4444"
    restart: always
    depends_on:
      - db
  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ager
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ager-pgdata:/var/lib/postgresql/data
volumes:
  ager-pgdata: